# Generated by Django 5.1.15 on 2026-05-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_initial'),
        ('media_library', '0002_initial'),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_events', to='devices.device')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_events', to='media_library.media')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_events', to='playlists.playlist')),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['device', 'played_at'], name='analytics_p_device__10e326_idx'), models.Index(fields=['media', 'played_at'], name='analytics_p_media_i_2be113_idx')],
            },
        ),
    ]
