# Generated by Django 5.1.15 on 2026-05-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('channel', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta')], db_index=True, default='stable', max_length=16)),
                ('os', models.CharField(choices=[('linux', 'Linux'), ('darwin', 'macOS'), ('windows', 'Windows')], db_index=True, max_length=16)),
                ('arch', models.CharField(choices=[('amd64', 'x86-64'), ('arm64', 'ARM64'), ('arm', 'ARM (32-bit)')], db_index=True, max_length=16)),
                ('download_url', models.URLField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('signature', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'os', 'arch', 'is_active'], name='releases_re_channel_a0497c_idx')],
            },
        ),
    ]
