# Generated by Django 5.1.15 on 2026-05-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_initial'),
        ('playlists', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g. Morning, Lunch', max_length=100)),
                ('days_of_week', models.JSONField(default=list)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher wins when schedules overlap')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='devices.device')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='playlists.playlist')),
            ],
            options={
                'ordering': ['priority', 'start_time'],
            },
        ),
    ]
